# Generated by Django 4.2.4 on 2023-08-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_tag_scopearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopearticle',
            name='scope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.scope'),
            preserve_default=False,
        ),
    ]
