# Generated by Django 4.2.4 on 2023-08-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_scope_options_remove_scopearticle_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopearticle',
            options={'verbose_name': 'Тематики статьи', 'verbose_name_plural': 'Тематики статей'},
        ),
        migrations.AddField(
            model_name='scope',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
            preserve_default=False,
        ),
    ]
