# Generated by Django 4.2.4 on 2023-08-07 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_scopearticle_options_scope_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='article',
        ),
        migrations.AddField(
            model_name='scopearticle',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
            preserve_default=False,
        ),
    ]
