# Generated by Django 4.2.4 on 2023-08-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_scope_article_scopearticle_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopearticle',
            name='scope',
        ),
        migrations.DeleteModel(
            name='Scope',
        ),
    ]
