# Generated by Django 4.2.4 on 2023-08-07 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_scopearticle_is_main_alter_scopearticle_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
